PACMAN_ANDROID_PKG_NAME="fastfetch"
PACMAN_ANDROID_PKG_VERSION="2.66.0"
PACMAN_ANDROID_PKG_REVERSION="3"
PACMAN_ANDROID_PKG_DESCRIPTION="Fast neofetch-like system information tool"
PACMAN_ANDROID_PKG_URL="https://github.com/fastfetch-cli/fastfetch"
PACMAN_ANDROID_PKG_LICENSES=("MIT")
PACMAN_ANDROID_PKG_TARGETS=("x86_64" "i686" "armhf" "aarch64")
PACMAN_ANDROID_PKG_SRCURL="https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/${PACMAN_ANDROID_PKG_VERSION}.tar.gz"
PACMAN_ANDROID_PKG_SHA256="547883c2f0dbc85a4545d4533f5b812fbc4c8ffe1271056de18b51994acbf474"
PACMAN_ANDROID_PKG_SOURCE_DIRNAME="fastfetch-${PACMAN_ANDROID_PKG_VERSION}"
PACMAN_ANDROID_PKG_BUILD_SYSTEM="cmake"

case "$PACMAN_ANDROID_TARGET" in
  x86_64) pacman_android_fastfetch_processor_override="x86_64" ;;
  i686) pacman_android_fastfetch_processor_override="i686" ;;
  armhf) pacman_android_fastfetch_processor_override="armv7l" ;;
  aarch64) pacman_android_fastfetch_processor_override="aarch64" ;;
  *)
    echo "unsupported fastfetch target: $PACMAN_ANDROID_TARGET" >&2
    exit 1
    ;;
esac

PACMAN_ANDROID_PKG_EXTRA_CONFIGURE_ARGS=(
  "-DTARGET_DIR_ROOT=$PACMAN_ROOTDIR"
  "-DTARGET_DIR_USR=$PACMAN_ROOTDIR/usr"
  "-DTARGET_DIR_HOME=$PACMAN_ROOTDIR/home"
  "-DTARGET_DIR_ETC=$PACMAN_ROOTDIR/etc"
  "-DCMAKE_SYSTEM_PROCESSOR_OVERRIDE=$pacman_android_fastfetch_processor_override"
  "-DBUILD_FLASHFETCH=OFF"
  "-DBUILD_TESTS=OFF"
  "-DSET_TWEAK=OFF"
  "-DINSTALL_LICENSE=ON"
  "-DENABLE_VULKAN=OFF"
  "-DENABLE_WAYLAND=OFF"
  "-DENABLE_XCB_RANDR=OFF"
  "-DENABLE_XRANDR=OFF"
  "-DENABLE_DRM=OFF"
  "-DENABLE_VADRM=OFF"
  "-DENABLE_VAX11=OFF"
  "-DENABLE_VDPAU=OFF"
  "-DENABLE_GIO=OFF"
  "-DENABLE_DCONF=OFF"
  "-DENABLE_EET=OFF"
  "-DENABLE_DBUS=OFF"
  "-DENABLE_SQLITE3=OFF"
  "-DENABLE_RPM=OFF"
  "-DENABLE_IMAGEMAGICK7=OFF"
  "-DENABLE_IMAGEMAGICK6=OFF"
  "-DENABLE_CHAFA=OFF"
  "-DENABLE_EGL=OFF"
  "-DENABLE_GLX=OFF"
  "-DENABLE_OPENCL=OFF"
  "-DENABLE_FREETYPE=OFF"
  "-DENABLE_PULSE=OFF"
  "-DENABLE_DDCUTIL=OFF"
  "-DENABLE_ELF=OFF"
  "-DENABLE_ZLIB=ON"
  "-DENABLE_LUA=OFF"
  "-DENABLE_QUICKJS=OFF"
  "-DENABLE_LIBZFS=OFF"
  "-DENABLE_THREADS=ON"
  "-DMODULE_DISABLE_OPENGL=ON"
  "-DBINARY_LINK_TYPE=dlopen"
)

pacman_android_recipe_post_install() {
  install -Dm644 \
    "$PACMAN_ANDROID_SOURCE_WORKTREE/LICENSE" \
    "$PACMAN_ANDROID_ROOTFS_DIR/usr/share/licenses/$PACMAN_ANDROID_PKG_NAME/LICENSE.upstream"

  install -Dm644 \
    "$PACMAN_ANDROID_SOURCE_WORKTREE/README.md" \
    "$PACMAN_ANDROID_ROOTFS_DIR/usr/share/doc/$PACMAN_ANDROID_PKG_NAME/README.upstream.md"
}
