PACMAN_ANDROID_PKG_NAME="glibc"
PACMAN_ANDROID_PKG_VERSION="2.43.9000"
PACMAN_ANDROID_PKG_REVERSION="1"
PACMAN_ANDROID_PKG_DESCRIPTION="The GNU C Library provides many of the low-level components used directly by programs written in the C or C++ languages."
PACMAN_ANDROID_PKG_URL="https://sourceware.org/git/glibc.git"
PACMAN_ANDROID_PKG_LICENSES=("MIT")
PACMAN_ANDROID_PKG_TARGETS=("x86_64" "i686" "armhf" "aarch64")
PACMAN_ANDROID_PKG_SRCURL="https://github.com/xingguangcuican6666/glibc-pacman-android/archive/refs/tags/v${PACMAN_ANDROID_PKG_VERSION}.tar.gz"
PACMAN_ANDROID_PKG_SHA256="48018955c54feca2cd3754f0522098865272452f00ce1dbad897b1a10308edfc"
PACMAN_ANDROID_PKG_SOURCE_DIRNAME="glibc-${PACMAN_ANDROID_PKG_VERSION}"
