PACMAN_ANDROID_SUBPKG_DESCRIPTION="Runtime libraries shipped by GCC"
PACMAN_ANDROID_SUBPKG_ALLOW_EMPTY="true"
PACMAN_ANDROID_SUBPKG_DEPENDS=(
  "glibc"
  "libasan=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
  "libatomic=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
  "libgcc=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
  "libgfortran=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
  "libgomp=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
  "libobjc=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
  "libstdc++=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
  "libubsan=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
)

case "$PACMAN_ANDROID_TARGET" in
  x86_64|i686)
    PACMAN_ANDROID_SUBPKG_DEPENDS+=("libquadmath=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}")
    ;;
esac

case "$PACMAN_ANDROID_TARGET" in
  x86_64|aarch64)
    PACMAN_ANDROID_SUBPKG_DEPENDS+=(
      "libhwasan=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
      "liblsan=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
      "libtsan=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}"
    )
    ;;
esac
