PACMAN_ANDROID_SUBPKG_DESCRIPTION="Address Sanitizer runtime library shipped by GCC"
PACMAN_ANDROID_SUBPKG_DEPENDS=("glibc" "libgcc=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}" "libstdc++=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}")
PACMAN_ANDROID_SUBPKG_PROVIDES=("libasan.so")
PACMAN_ANDROID_SUBPKG_INCLUDE_PATTERNS=("usr/lib/libasan.a" "usr/lib/libasan.so*")
