PACMAN_ANDROID_SUBPKG_DESCRIPTION="Low-level runtime library shipped by GCC"
PACMAN_ANDROID_SUBPKG_DEPENDS=("glibc")
PACMAN_ANDROID_SUBPKG_PROVIDES=("libgcc_s.so")
PACMAN_ANDROID_SUBPKG_INCLUDE_PATTERNS=("usr/lib/libgcc_s.so.*")
