PACMAN_ANDROID_SUBPKG_DESCRIPTION="Leak Sanitizer runtime library shipped by GCC"
PACMAN_ANDROID_SUBPKG_DEPENDS=("glibc" "libgcc=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}" "libstdc++=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}")
PACMAN_ANDROID_SUBPKG_PROVIDES=("liblsan.so")
PACMAN_ANDROID_SUBPKG_TARGETS=("x86_64" "aarch64")
PACMAN_ANDROID_SUBPKG_INCLUDE_PATTERNS=("usr/lib/liblsan.a" "usr/lib/liblsan.so*")
