PACMAN_ANDROID_SUBPKG_DESCRIPTION="Objective-C runtime libraries shipped by GCC"
PACMAN_ANDROID_SUBPKG_DEPENDS=("glibc" "libgcc=${PACMAN_ANDROID_PKG_VERSION}-${PACMAN_ANDROID_PKG_REVERSION}")
PACMAN_ANDROID_SUBPKG_PROVIDES=("libobjc.so")
PACMAN_ANDROID_SUBPKG_INCLUDE_PATTERNS=("usr/lib/libobjc.a" "usr/lib/libobjc.so*")
