PACMAN_ANDROID_PKG_NAME="fastfetch"
PACMAN_ANDROID_PKG_VERSION="2.66.0"
PACMAN_ANDROID_PKG_RELEASE="3"
PACMAN_ANDROID_PKG_DESCRIPTION="Fast neofetch-like system information tool"
PACMAN_ANDROID_PKG_URL="https://github.com/fastfetch-cli/fastfetch"
PACMAN_ANDROID_PKG_LICENSES=("MIT")
PACMAN_ANDROID_PKG_TARGETS=("x86_64" "i686" "armhf" "aarch64")

PACMAN_ANDROID_FASTFETCH_TAG="2.66.0"
PACMAN_ANDROID_FASTFETCH_COMMIT="08698098579bb8b043b0a343159b8018f5cea4fc"
PACMAN_ANDROID_FASTFETCH_SOURCE_URL="https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.66.0.tar.gz"
PACMAN_ANDROID_FASTFETCH_SOURCE_SHA256="547883c2f0dbc85a4545d4533f5b812fbc4c8ffe1271056de18b51994acbf474"

pacman_android_recipe_prepare() {
  export PACMAN_ANDROID_DISTFILES_DIR="$PACMAN_ANDROID_REPO_ROOT/out/distfiles"
  export PACMAN_ANDROID_SOURCE_ARCHIVE="$PACMAN_ANDROID_DISTFILES_DIR/fastfetch-${PACMAN_ANDROID_FASTFETCH_TAG}.tar.gz"
  export PACMAN_ANDROID_SOURCE_DIR="$PACMAN_ANDROID_BUILD_ROOT/src"
  export PACMAN_ANDROID_SOURCE_WORKTREE="$PACMAN_ANDROID_SOURCE_DIR/fastfetch-${PACMAN_ANDROID_FASTFETCH_TAG}"
  export PACMAN_ANDROID_CMAKE_BUILD_DIR="$PACMAN_ANDROID_BUILD_ROOT/cmake-build"

  mkdir -p "$PACMAN_ANDROID_DISTFILES_DIR" "$PACMAN_ANDROID_SOURCE_DIR"

  if [[ ! -f "$PACMAN_ANDROID_SOURCE_ARCHIVE" ]]; then
    curl \
      --fail \
      --location \
      --retry 5 \
      --retry-all-errors \
      --output "$PACMAN_ANDROID_SOURCE_ARCHIVE" \
      "$PACMAN_ANDROID_FASTFETCH_SOURCE_URL"
  fi

  echo "${PACMAN_ANDROID_FASTFETCH_SOURCE_SHA256}  ${PACMAN_ANDROID_SOURCE_ARCHIVE}" | sha256sum --check --status

  rm -rf "$PACMAN_ANDROID_SOURCE_WORKTREE" "$PACMAN_ANDROID_CMAKE_BUILD_DIR"
  tar -xf "$PACMAN_ANDROID_SOURCE_ARCHIVE" -C "$PACMAN_ANDROID_SOURCE_DIR"
}


pacman_android_recipe_build() {
  local toolchain_file="$PACMAN_ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake"
  local processor_override=""

  case "$PACMAN_ANDROID_TARGET" in
    x86_64) processor_override="x86_64" ;;
    i686) processor_override="i686" ;;
    armhf) processor_override="armv7l" ;;
    aarch64) processor_override="aarch64" ;;
  esac

  cmake -S "$PACMAN_ANDROID_SOURCE_WORKTREE" -B "$PACMAN_ANDROID_CMAKE_BUILD_DIR" -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="$toolchain_file" \
    -DANDROID_ABI="$PACMAN_ANDROID_ABI" \
    -DANDROID_PLATFORM="android-$PACMAN_ANDROID_API_LEVEL" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$PACMAN_ANDROID_PREFIX" \
    -DCMAKE_INSTALL_SYSCONFDIR="$PACMAN_ANDROID_SYSCONFDIR" \
    -DTARGET_DIR_ROOT="$PACMAN_ROOTDIR" \
    -DTARGET_DIR_USR="$PACMAN_ROOTDIR/usr" \
    -DTARGET_DIR_HOME="$PACMAN_ROOTDIR/home" \
    -DTARGET_DIR_ETC="$PACMAN_ROOTDIR/etc" \
    -DCMAKE_SYSTEM_PROCESSOR_OVERRIDE="$processor_override" \
    -DBUILD_FLASHFETCH=OFF \
    -DBUILD_TESTS=OFF \
    -DSET_TWEAK=OFF \
    -DINSTALL_LICENSE=ON \
    -DENABLE_VULKAN=OFF \
    -DENABLE_WAYLAND=OFF \
    -DENABLE_XCB_RANDR=OFF \
    -DENABLE_XRANDR=OFF \
    -DENABLE_DRM=OFF \
    -DENABLE_VADRM=OFF \
    -DENABLE_VAX11=OFF \
    -DENABLE_VDPAU=OFF \
    -DENABLE_GIO=OFF \
    -DENABLE_DCONF=OFF \
    -DENABLE_EET=OFF \
    -DENABLE_DBUS=OFF \
    -DENABLE_SQLITE3=OFF \
    -DENABLE_RPM=OFF \
    -DENABLE_IMAGEMAGICK7=OFF \
    -DENABLE_IMAGEMAGICK6=OFF \
    -DENABLE_CHAFA=OFF \
    -DENABLE_EGL=OFF \
    -DENABLE_GLX=OFF \
    -DENABLE_OPENCL=OFF \
    -DENABLE_FREETYPE=OFF \
    -DENABLE_PULSE=OFF \
    -DENABLE_DDCUTIL=OFF \
    -DENABLE_ELF=OFF \
    -DENABLE_ZLIB=ON \
    -DENABLE_LUA=OFF \
    -DENABLE_QUICKJS=OFF \
    -DENABLE_LIBZFS=OFF \
    -DENABLE_THREADS=ON \
    -DMODULE_DISABLE_OPENGL=ON \
    -DBINARY_LINK_TYPE=dlopen

  cmake --build "$PACMAN_ANDROID_CMAKE_BUILD_DIR" --parallel
}


pacman_android_recipe_install() {
  DESTDIR="$PACMAN_ANDROID_ROOTFS_DIR" \
    cmake --install "$PACMAN_ANDROID_CMAKE_BUILD_DIR"

  install -Dm644 \
    "$PACMAN_ANDROID_SOURCE_WORKTREE/LICENSE" \
    "$PACMAN_ANDROID_ROOTFS_DIR/usr/share/licenses/$PACMAN_ANDROID_PKG_NAME/LICENSE.upstream"

  install -Dm644 \
    "$PACMAN_ANDROID_SOURCE_WORKTREE/README.md" \
    "$PACMAN_ANDROID_ROOTFS_DIR/usr/share/doc/$PACMAN_ANDROID_PKG_NAME/README.upstream.md"
}
